"""
Tool call models for the Trading Engine.

These models represent the tool calls generated by the LLM
and validated by the TradeCompiler.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Dict, List, Optional, Any


class ToolCall(BaseModel):
    """
    Model for a tool call proposed by the LLM.
    
    This represents an action to be taken on the exchange via CCXT MCP.
    """
    tool: str = Field(description="The name of the tool to call")
    parameters: Dict[str, Any] = Field(description="The parameters for the tool call")
    
    @field_validator("parameters")
    @classmethod
    def normalize_parameters(cls, params: Dict) -> Dict:
        """
        Normalize parameter keys (e.g., handle camelCase, quoted keys).
        
        This is crucial for fixing the common issue where the LLM returns
        keys like '"type"' instead of 'type'.
        """
        if not params:
            return {}
            
        normalized = {}
        for k, v in params.items():
            # Handle quoted keys like '"type"'
            if isinstance(k, str) and len(k) > 2 and k.startswith('"') and k.endswith('"'):
                k = k[1:-1]
                
            # Standardize common variations
            if k.lower() in ["ordertype", "order_type"]:
                k = "type"
                
            normalized[k] = v
            
        return normalized


class ValidatedToolCall(BaseModel):
    """
    Model for a validated tool call ready for execution.
    
    This represents a tool call that has been validated by the TradeCompiler
    and is ready for execution.
    """
    tool: str = Field(description="The name of the tool to call")
    parameters: Dict[str, Any] = Field(description="The validated parameters for the tool call")
    original_call: Optional[ToolCall] = Field(
        default=None, 
        description="Reference to original call for debugging"
    )