"""
Symbol Registry - Centralized symbol definitions for all formats

This registry contains all supported trading pairs across different systems:
- ggShot: BTCUSDT (no separator) 
- CCXT: BTC/USDT (slash separator)
- Hummingbot: BTC-USDT (dash separator)
- Platform: BTC-USDT (standardized format)
"""

from typing import Dict, List, Optional

# Base symbol registry - built from 141 ggShot symbols
SYMBOL_REGISTRY = {
    # Major cryptocurrencies
    "1inch": {
        "base": "1INCH",
        "quote": "USDT",
        "ggshot": "1INCHUSDT",
        "ccxt": "1INCH/USDT",
        "hummingbot": "1INCH-USDT",
        "platform": "1INCH-USDT",
        "coingecko_id": "1inch",
        "symphony": "1INCH",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "aave": {
        "base": "AAVE", 
        "quote": "USDT",
        "ggshot": "AAVEUSDT",
        "ccxt": "AAVE/USDT",
        "hummingbot": "AAVE-USDT",
        "platform": "AAVE-USDT",
        "coingecko_id": "aave",
        "symphony": "AAVE",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "ach": {
        "base": "ACH",
        "quote": "USDT", 
        "ggshot": "ACHUSDT",
        "ccxt": "ACH/USDT",
        "hummingbot": "ACH-USDT",
        "platform": "ACH-USDT",
        "coingecko_id": "alchemy-pay",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "ada": {
        "base": "ADA",
        "quote": "USDT",
        "ggshot": "ADAUSDT", 
        "ccxt": "ADA/USDT",
        "hummingbot": "ADA-USDT",
        "platform": "ADA-USDT",
        "coingecko_id": "cardano",
        "symphony": "ADA",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "algo": {
        "base": "ALGO",
        "quote": "USDT",
        "ggshot": "ALGOUSDT",
        "ccxt": "ALGO/USDT", 
        "hummingbot": "ALGO-USDT",
        "platform": "ALGO-USDT",
        "coingecko_id": "algorand",
        "symphony": "ALGO",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "alice": {
        "base": "ALICE",
        "quote": "USDT",
        "ggshot": "ALICEUSDT",
        "ccxt": "ALICE/USDT",
        "hummingbot": "ALICE-USDT",
        "platform": "ALICE-USDT",
        "coingecko_id": "my-neighbor-alice",
        "symphony": "ALICE",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "alpha": {
        "base": "ALPHA",
        "quote": "USDT",
        "ggshot": "ALPHAUSDT",
        "ccxt": "ALPHA/USDT",
        "hummingbot": "ALPHA-USDT", 
        "platform": "ALPHA-USDT",
        "coingecko_id": "alpha-finance",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "alt": {
        "base": "ALT",
        "quote": "USDT",
        "ggshot": "ALTUSDT",
        "ccxt": "ALT/USDT",
        "hummingbot": "ALT-USDT",
        "platform": "ALT-USDT",
        "coingecko_id": "altlayer",
        "symphony": "ALT",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "ankr": {
        "base": "ANKR",
        "quote": "USDT",
        "ggshot": "ANKRUSDT",
        "ccxt": "ANKR/USDT",
        "hummingbot": "ANKR-USDT",
        "platform": "ANKR-USDT",
        "coingecko_id": "ankr",
        "symphony": "ANKR",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "ape": {
        "base": "APE", 
        "quote": "USDT",
        "ggshot": "APEUSDT",
        "ccxt": "APE/USDT",
        "hummingbot": "APE-USDT",
        "platform": "APE-USDT",
        "coingecko_id": "apecoin",
        "symphony": "APE",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "api3": {
        "base": "API3",
        "quote": "USDT",
        "ggshot": "API3USDT",
        "ccxt": "API3/USDT",
        "hummingbot": "API3-USDT",
        "platform": "API3-USDT",
        "coingecko_id": "api3",
        "symphony": "API3",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "apt": {
        "base": "APT",
        "quote": "USDT",
        "ggshot": "APTUSDT",
        "ccxt": "APT/USDT",
        "hummingbot": "APT-USDT",
        "platform": "APT-USDT",
        "coingecko_id": "aptos",
        "symphony": "APT",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "arb": {
        "base": "ARB",
        "quote": "USDT",
        "ggshot": "ARBUSDT",
        "ccxt": "ARB/USDT",
        "hummingbot": "ARB-USDT",
        "platform": "ARB-USDT",
        "coingecko_id": "arbitrum",
        "symphony": "ARB",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "arkm": {
        "base": "ARKM",
        "quote": "USDT",
        "ggshot": "ARKMUSDT",
        "ccxt": "ARKM/USDT",
        "hummingbot": "ARKM-USDT",
        "platform": "ARKM-USDT",
        "coingecko_id": "arkham",
        "symphony": "ARKM",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "ar": {
        "base": "AR",
        "quote": "USDT",
        "ggshot": "ARUSDT", 
        "ccxt": "AR/USDT",
        "hummingbot": "AR-USDT",
        "platform": "AR-USDT",
        "coingecko_id": "arweave",
        "symphony": "AR",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "astr": {
        "base": "ASTR",
        "quote": "USDT",
        "ggshot": "ASTRUSDT",
        "ccxt": "ASTR/USDT",
        "hummingbot": "ASTR-USDT",
        "platform": "ASTR-USDT",
        "coingecko_id": "astar",
        "symphony": "ASTR",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "atom": {
        "base": "ATOM",
        "quote": "USDT",
        "ggshot": "ATOMUSDT",
        "ccxt": "ATOM/USDT",
        "hummingbot": "ATOM-USDT",
        "platform": "ATOM-USDT",
        "coingecko_id": "cosmos",
        "symphony": "ATOM",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "auction": {
        "base": "AUCTION",
        "quote": "USDT",
        "ggshot": "AUCTIONUSDT",
        "ccxt": "AUCTION/USDT",
        "hummingbot": "AUCTION-USDT",
        "platform": "AUCTION-USDT",
        "coingecko_id": "bounce-finance-governance-token",
        "symphony": "AUCTION",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "avax": {
        "base": "AVAX",
        "quote": "USDT",
        "ggshot": "AVAXUSDT",
        "ccxt": "AVAX/USDT",
        "hummingbot": "AVAX-USDT",
        "platform": "AVAX-USDT",
        "coingecko_id": "avalanche-2",
        "symphony": "AVAX",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "axs": {
        "base": "AXS",
        "quote": "USDT",
        "ggshot": "AXSUSDT",
        "ccxt": "AXS/USDT",
        "hummingbot": "AXS-USDT",
        "platform": "AXS-USDT",
        "coingecko_id": "axie-infinity",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "bake": {
        "base": "BAKE",
        "quote": "USDT",
        "ggshot": "BAKEUSDT",
        "ccxt": "BAKE/USDT",
        "hummingbot": "BAKE-USDT",
        "platform": "BAKE-USDT", 
        "coingecko_id": "bakerytoken",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "bal": {
        "base": "BAL",
        "quote": "USDT",
        "ggshot": "BALUSDT",
        "ccxt": "BAL/USDT",
        "hummingbot": "BAL-USDT",
        "platform": "BAL-USDT",
        "coingecko_id": "balancer",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "band": {
        "base": "BAND",
        "quote": "USDT",
        "ggshot": "BANDUSDT",
        "ccxt": "BAND/USDT", 
        "hummingbot": "BAND-USDT",
        "platform": "BAND-USDT",
        "coingecko_id": "band-protocol",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "bat": {
        "base": "BAT",
        "quote": "USDT",
        "ggshot": "BATUSDT",
        "ccxt": "BAT/USDT",
        "hummingbot": "BAT-USDT",
        "platform": "BAT-USDT",
        "coingecko_id": "basic-attention-token",
        "symphony": "BAT",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "bch": {
        "base": "BCH",
        "quote": "USDT",
        "ggshot": "BCHUSDT",
        "ccxt": "BCH/USDT",
        "hummingbot": "BCH-USDT",
        "platform": "BCH-USDT",
        "coingecko_id": "bitcoin-cash",
        "symphony": "BCH",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "bel": {
        "base": "BEL",
        "quote": "USDT", 
        "ggshot": "BELUSDT",
        "ccxt": "BEL/USDT",
        "hummingbot": "BEL-USDT",
        "platform": "BEL-USDT",
        "coingecko_id": "bella-protocol",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "bigtime": {
        "base": "BIGTIME",
        "quote": "USDT",
        "ggshot": "BIGTIMEUSDT",
        "ccxt": "BIGTIME/USDT",
        "hummingbot": "BIGTIME-USDT",
        "platform": "BIGTIME-USDT",
        "coingecko_id": "big-time",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "bnb": {
        "base": "BNB",
        "quote": "USDT",
        "ggshot": "BNBUSDT",
        "ccxt": "BNB/USDT",
        "hummingbot": "BNB-USDT",
        "platform": "BNB-USDT",
        "coingecko_id": "binancecoin",
        "symphony": "BNB",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "bnt": {
        "base": "BNT",
        "quote": "USDT",
        "ggshot": "BNTUSDT",
        "ccxt": "BNT/USDT",
        "hummingbot": "BNT-USDT",
        "platform": "BNT-USDT",
        "coingecko_id": "bancor",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "bome": {
        "base": "BOME",
        "quote": "USDT",
        "ggshot": "BOMEUSDT",
        "ccxt": "BOME/USDT",
        "hummingbot": "BOME-USDT",
        "platform": "BOME-USDT", 
        "coingecko_id": "book-of-meme",
        "symphony": "BOME",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "btc": {
        "base": "BTC",
        "quote": "USDT",
        "ggshot": "BTCUSDT",
        "ccxt": "BTC/USDT", 
        "hummingbot": "BTC-USDT",
        "platform": "BTC-USDT",
        "coingecko_id": "bitcoin",
        "symphony": "BTC",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "cake": {
        "base": "CAKE",
        "quote": "USDT",
        "ggshot": "CAKEUSDT",
        "ccxt": "CAKE/USDT",
        "hummingbot": "CAKE-USDT",
        "platform": "CAKE-USDT",
        "coingecko_id": "pancakeswap-token",
        "symphony": "CAKE",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "celr": {
        "base": "CELR",
        "quote": "USDT",
        "ggshot": "CELRUSDT",
        "ccxt": "CELR/USDT",
        "hummingbot": "CELR-USDT",
        "platform": "CELR-USDT",
        "coingecko_id": "celer-network",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "cetus": {
        "base": "CETUS",
        "quote": "USDT",
        "ggshot": "CETUSUSDT",
        "ccxt": "CETUS/USDT",
        "hummingbot": "CETUS-USDT",
        "platform": "CETUS-USDT",
        "coingecko_id": "cetus-protocol",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "cfx": {
        "base": "CFX",
        "quote": "USDT",
        "ggshot": "CFXUSDT",
        "ccxt": "CFX/USDT",
        "hummingbot": "CFX-USDT",
        "platform": "CFX-USDT",
        "coingecko_id": "conflux-token",
        "symphony": "CFX",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "chr": {
        "base": "CHR", 
        "quote": "USDT",
        "ggshot": "CHRUSDT",
        "ccxt": "CHR/USDT",
        "hummingbot": "CHR-USDT",
        "platform": "CHR-USDT",
        "coingecko_id": "chromaway",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "chz": {
        "base": "CHZ",
        "quote": "USDT",
        "ggshot": "CHZUSDT",
        "ccxt": "CHZ/USDT",
        "hummingbot": "CHZ-USDT", 
        "platform": "CHZ-USDT",
        "coingecko_id": "chiliz",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "comp": {
        "base": "COMP",
        "quote": "USDT",
        "ggshot": "COMPUSDT",
        "ccxt": "COMP/USDT",
        "hummingbot": "COMP-USDT",
        "platform": "COMP-USDT",
        "coingecko_id": "compound-governance-token",
        "symphony": "COMP",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "coti": {
        "base": "COTI",
        "quote": "USDT",
        "ggshot": "COTIUSDT",
        "ccxt": "COTI/USDT",
        "hummingbot": "COTI-USDT",
        "platform": "COTI-USDT",
        "coingecko_id": "coti",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "crv": {
        "base": "CRV",
        "quote": "USDT",
        "ggshot": "CRVUSDT",
        "ccxt": "CRV/USDT",
        "hummingbot": "CRV-USDT",
        "platform": "CRV-USDT",
        "coingecko_id": "curve-dao-token",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": True,
        "websocket_cached": False
    },
    "cyber": {
        "base": "CYBER",
        "quote": "USDT",
        "ggshot": "CYBERUSDT",
        "ccxt": "CYBER/USDT",
        "hummingbot": "CYBER-USDT",
        "platform": "CYBER-USDT",
        "coingecko_id": "cyberconnect",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "dash": {
        "base": "DASH", 
        "quote": "USDT",
        "ggshot": "DASHUSDT",
        "ccxt": "DASH/USDT",
        "hummingbot": "DASH-USDT",
        "platform": "DASH-USDT",
        "coingecko_id": "dash",
        "symphony": "DASH",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "doge": {
        "base": "DOGE",
        "quote": "USDT",
        "ggshot": "DOGEUSDT",
        "ccxt": "DOGE/USDT",
        "hummingbot": "DOGE-USDT",
        "platform": "DOGE-USDT",
        "coingecko_id": "dogecoin",
        "symphony": "DOGE",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "dot": {
        "base": "DOT",
        "quote": "USDT",
        "ggshot": "DOTUSDT",
        "ccxt": "DOT/USDT",
        "hummingbot": "DOT-USDT",
        "platform": "DOT-USDT",
        "coingecko_id": "polkadot",
        "symphony": "DOT",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "dydx": {
        "base": "DYDX",
        "quote": "USDT",
        "ggshot": "DYDXUSDT",
        "ccxt": "DYDX/USDT",
        "hummingbot": "DYDX-USDT",
        "platform": "DYDX-USDT",
        "coingecko_id": "dydx",
        "symphony": "DYDX",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "egld": {
        "base": "EGLD",
        "quote": "USDT",
        "ggshot": "EGLDUSDT",
        "ccxt": "EGLD/USDT", 
        "hummingbot": "EGLD-USDT",
        "platform": "EGLD-USDT",
        "coingecko_id": "elrond-erd-2",
        "symphony": "EGLD",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "ena": {
        "base": "ENA",
        "quote": "USDT",
        "ggshot": "ENAUSDT",
        "ccxt": "ENA/USDT",
        "hummingbot": "ENA-USDT",
        "platform": "ENA-USDT",
        "coingecko_id": "ethena",
        "symphony": "ENA",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "ens": {
        "base": "ENS", 
        "quote": "USDT",
        "ggshot": "ENSUSDT",
        "ccxt": "ENS/USDT",
        "hummingbot": "ENS-USDT",
        "platform": "ENS-USDT",
        "coingecko_id": "ethereum-name-service",
        "symphony": "ENS",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "etc": {
        "base": "ETC",
        "quote": "USDT",
        "ggshot": "ETCUSDT",
        "ccxt": "ETC/USDT",
        "hummingbot": "ETC-USDT",
        "platform": "ETC-USDT",
        "coingecko_id": "ethereum-classic",
        "symphony": "ETC",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "eth": {
        "base": "ETH",
        "quote": "USDT",
        "ggshot": "ETHUSDT",
        "ccxt": "ETH/USDT",
        "hummingbot": "ETH-USDT",
        "platform": "ETH-USDT",
        "coingecko_id": "ethereum",
        "symphony": "ETH",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "ethfi": {
        "base": "ETHFI",
        "quote": "USDT",
        "ggshot": "ETHFIUSDT",
        "ccxt": "ETHFI/USDT",
        "hummingbot": "ETHFI-USDT",
        "platform": "ETHFI-USDT",
        "coingecko_id": "ether-fi",
        "symphony": "ETHFI",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "fet": {
        "base": "FET",
        "quote": "USDT",
        "ggshot": "FETUSDT", 
        "ccxt": "FET/USDT",
        "hummingbot": "FET-USDT",
        "platform": "FET-USDT",
        "coingecko_id": "fetch-ai",
        "symphony": "FET",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "fil": {
        "base": "FIL",
        "quote": "USDT",
        "ggshot": "FILUSDT",
        "ccxt": "FIL/USDT",
        "hummingbot": "FIL-USDT",
        "platform": "FIL-USDT",
        "coingecko_id": "filecoin",
        "symphony": "FIL",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "flm": {
        "base": "FLM",
        "quote": "USDT",
        "ggshot": "FLMUSDT",
        "ccxt": "FLM/USDT",
        "hummingbot": "FLM-USDT",
        "platform": "FLM-USDT",
        "coingecko_id": "flamingo-finance",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "flow": {
        "base": "FLOW",
        "quote": "USDT",
        "ggshot": "FLOWUSDT",
        "ccxt": "FLOW/USDT",
        "hummingbot": "FLOW-USDT",
        "platform": "FLOW-USDT",
        "coingecko_id": "flow",
        "symphony": "FLOW",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "gala": {
        "base": "GALA",
        "quote": "USDT",
        "ggshot": "GALAUSDT",
        "ccxt": "GALA/USDT",
        "hummingbot": "GALA-USDT",
        "platform": "GALA-USDT",
        "coingecko_id": "gala",
        "symphony": "GALA",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "gmt": {
        "base": "GMT",
        "quote": "USDT", 
        "ggshot": "GMTUSDT",
        "ccxt": "GMT/USDT",
        "hummingbot": "GMT-USDT",
        "platform": "GMT-USDT",
        "coingecko_id": "stepn",
        "symphony": "GMT",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "gmx": {
        "base": "GMX",
        "quote": "USDT",
        "ggshot": "GMXUSDT",
        "ccxt": "GMX/USDT",
        "hummingbot": "GMX-USDT",
        "platform": "GMX-USDT",
        "coingecko_id": "gmx",
        "symphony": "GMX",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "grt": {
        "base": "GRT",
        "quote": "USDT",
        "ggshot": "GRTUSDT",
        "ccxt": "GRT/USDT",
        "hummingbot": "GRT-USDT",
        "platform": "GRT-USDT",
        "coingecko_id": "the-graph",
        "symphony": "GRT",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "gtc": {
        "base": "GTC",
        "quote": "USDT",
        "ggshot": "GTCUSDT",
        "ccxt": "GTC/USDT",
        "hummingbot": "GTC-USDT",
        "platform": "GTC-USDT",
        "coingecko_id": "gitcoin",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "hbar": {
        "base": "HBAR",
        "quote": "USDT",
        "ggshot": "HBARUSDT",
        "ccxt": "HBAR/USDT",
        "hummingbot": "HBAR-USDT",
        "platform": "HBAR-USDT",
        "coingecko_id": "hedera-hashgraph",
        "symphony": "HBAR",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "high": {
        "base": "HIGH",
        "quote": "USDT",
        "ggshot": "HIGHUSDT",
        "ccxt": "HIGH/USDT",
        "hummingbot": "HIGH-USDT",
        "platform": "HIGH-USDT",
        "coingecko_id": "highstreet",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "hook": {
        "base": "HOOK",
        "quote": "USDT",
        "ggshot": "HOOKUSDT", 
        "ccxt": "HOOK/USDT",
        "hummingbot": "HOOK-USDT",
        "platform": "HOOK-USDT",
        "coingecko_id": "hooked-protocol",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "icp": {
        "base": "ICP",
        "quote": "USDT",
        "ggshot": "ICPUSDT",
        "ccxt": "ICP/USDT",
        "hummingbot": "ICP-USDT",
        "platform": "ICP-USDT",
        "coingecko_id": "internet-computer",
        "symphony": "ICP",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "icx": {
        "base": "ICX",
        "quote": "USDT",
        "ggshot": "ICXUSDT",
        "ccxt": "ICX/USDT",
        "hummingbot": "ICX-USDT",
        "platform": "ICX-USDT",
        "coingecko_id": "icon",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "id": {
        "base": "ID",
        "quote": "USDT",
        "ggshot": "IDUSDT",
        "ccxt": "ID/USDT",
        "hummingbot": "ID-USDT",
        "platform": "ID-USDT",
        "coingecko_id": "space-id",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "inj": {
        "base": "INJ",
        "quote": "USDT",
        "ggshot": "INJUSDT",
        "ccxt": "INJ/USDT",
        "hummingbot": "INJ-USDT",
        "platform": "INJ-USDT",
        "coingecko_id": "injective-protocol",
        "symphony": "INJ",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "iost": {
        "base": "IOST",
        "quote": "USDT",
        "ggshot": "IOSTUSDT", 
        "ccxt": "IOST/USDT",
        "hummingbot": "IOST-USDT",
        "platform": "IOST-USDT",
        "coingecko_id": "iostoken",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "iotx": {
        "base": "IOTX",
        "quote": "USDT",
        "ggshot": "IOTXUSDT",
        "ccxt": "IOTX/USDT",
        "hummingbot": "IOTX-USDT",
        "platform": "IOTX-USDT",
        "coingecko_id": "iotex",
        "symphony": "IOTX",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "jasmy": {
        "base": "JASMY",
        "quote": "USDT",
        "ggshot": "JASMYUSDT",
        "ccxt": "JASMY/USDT",
        "hummingbot": "JASMY-USDT",
        "platform": "JASMY-USDT",
        "coingecko_id": "jasmycoin",
        "symphony": "JASMY",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "jto": {
        "base": "JTO",
        "quote": "USDT",
        "ggshot": "JTOUSDT",
        "ccxt": "JTO/USDT",
        "hummingbot": "JTO-USDT",
        "platform": "JTO-USDT",
        "coingecko_id": "jito-governance-token",
        "symphony": "JTO",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "jup": {
        "base": "JUP",
        "quote": "USDT",
        "ggshot": "JUPUSDT",
        "ccxt": "JUP/USDT",
        "hummingbot": "JUP-USDT",
        "platform": "JUP-USDT",
        "coingecko_id": "jupiter-exchange-solana",
        "symphony": "JUP",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "kava": {
        "base": "KAVA",
        "quote": "USDT",
        "ggshot": "KAVAUSDT",
        "ccxt": "KAVA/USDT",
        "hummingbot": "KAVA-USDT",
        "platform": "KAVA-USDT",
        "coingecko_id": "kava",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "knc": {
        "base": "KNC",
        "quote": "USDT",
        "ggshot": "KNCUSDT",
        "ccxt": "KNC/USDT",
        "hummingbot": "KNC-USDT",
        "platform": "KNC-USDT",
        "coingecko_id": "kyber-network-crystal",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "ksm": {
        "base": "KSM",
        "quote": "USDT",
        "ggshot": "KSMUSDT",
        "ccxt": "KSM/USDT",
        "hummingbot": "KSM-USDT",
        "platform": "KSM-USDT",
        "coingecko_id": "kusama",
        "symphony": "KSM",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "ldo": {
        "base": "LDO",
        "quote": "USDT",
        "ggshot": "LDOUSDT",
        "ccxt": "LDO/USDT",
        "hummingbot": "LDO-USDT",
        "platform": "LDO-USDT",
        "coingecko_id": "lido-dao",
        "symphony": "LDO",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "lever": {
        "base": "LEVER",
        "quote": "USDT",
        "ggshot": "LEVERUSDT", 
        "ccxt": "LEVER/USDT",
        "hummingbot": "LEVER-USDT",
        "platform": "LEVER-USDT",
        "coingecko_id": "leverfi",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "link": {
        "base": "LINK",
        "quote": "USDT",
        "ggshot": "LINKUSDT",
        "ccxt": "LINK/USDT",
        "hummingbot": "LINK-USDT",
        "platform": "LINK-USDT",
        "coingecko_id": "chainlink",
        "symphony": "LINK",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "lpt": {
        "base": "LPT",
        "quote": "USDT",
        "ggshot": "LPTUSDT",
        "ccxt": "LPT/USDT",
        "hummingbot": "LPT-USDT",
        "platform": "LPT-USDT",
        "coingecko_id": "livepeer",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "lqty": {
        "base": "LQTY",
        "quote": "USDT",
        "ggshot": "LQTYUSDT",
        "ccxt": "LQTY/USDT",
        "hummingbot": "LQTY-USDT",
        "platform": "LQTY-USDT",
        "coingecko_id": "liquity",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "lrc": {
        "base": "LRC",
        "quote": "USDT",
        "ggshot": "LRCUSDT",
        "ccxt": "LRC/USDT",
        "hummingbot": "LRC-USDT",
        "platform": "LRC-USDT",
        "coingecko_id": "loopring",
        "symphony": "LRC",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "ltc": {
        "base": "LTC",
        "quote": "USDT",
        "ggshot": "LTCUSDT",
        "ccxt": "LTC/USDT",
        "hummingbot": "LTC-USDT",
        "platform": "LTC-USDT",
        "coingecko_id": "litecoin",
        "symphony": "LTC",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "magic": {
        "base": "MAGIC",
        "quote": "USDT",
        "ggshot": "MAGICUSDT",
        "ccxt": "MAGIC/USDT",
        "hummingbot": "MAGIC-USDT",
        "platform": "MAGIC-USDT",
        "coingecko_id": "magic",
        "symphony": "MAGIC",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "mana": {
        "base": "MANA",
        "quote": "USDT",
        "ggshot": "MANAUSDT",
        "ccxt": "MANA/USDT",
        "hummingbot": "MANA-USDT",
        "platform": "MANA-USDT",
        "coingecko_id": "decentraland",
        "symphony": "MANA",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "mask": {
        "base": "MASK",
        "quote": "USDT",
        "ggshot": "MASKUSDT",
        "ccxt": "MASK/USDT",
        "hummingbot": "MASK-USDT",
        "platform": "MASK-USDT",
        "coingecko_id": "mask-network",
        "symphony": "MASK",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "matic": {
        "base": "MATIC",
        "quote": "USDT",
        "ggshot": "MATICUSDT",
        "ccxt": "MATIC/USDT",
        "hummingbot": "MATIC-USDT",
        "platform": "MATIC-USDT",
        "coingecko_id": "matic-network",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "mkr": {
        "base": "MKR",
        "quote": "USDT",
        "ggshot": "MKRUSDT",
        "ccxt": "MKR/USDT",
        "hummingbot": "MKR-USDT",
        "platform": "MKR-USDT",
        "coingecko_id": "maker",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "near": {
        "base": "NEAR",
        "quote": "USDT",
        "ggshot": "NEARUSDT",
        "ccxt": "NEAR/USDT",
        "hummingbot": "NEAR-USDT", 
        "platform": "NEAR-USDT",
        "coingecko_id": "near",
        "symphony": "NEAR",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "neo": {
        "base": "NEO",
        "quote": "USDT",
        "ggshot": "NEOUSDT",
        "ccxt": "NEO/USDT",
        "hummingbot": "NEO-USDT",
        "platform": "NEO-USDT",
        "coingecko_id": "neo",
        "symphony": "NEO",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "nkn": {
        "base": "NKN",
        "quote": "USDT",
        "ggshot": "NKNUSDT",
        "ccxt": "NKN/USDT", 
        "hummingbot": "NKN-USDT",
        "platform": "NKN-USDT",
        "coingecko_id": "nkn",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "nmr": {
        "base": "NMR",
        "quote": "USDT",
        "ggshot": "NMRUSDT",
        "ccxt": "NMR/USDT",
        "hummingbot": "NMR-USDT",
        "platform": "NMR-USDT",
        "coingecko_id": "numeraire",
        "symphony": "NMR",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "not": {
        "base": "NOT",
        "quote": "USDT",
        "ggshot": "NOTUSDT",
        "ccxt": "NOT/USDT",
        "hummingbot": "NOT-USDT",
        "platform": "NOT-USDT",
        "coingecko_id": "notcoin",
        "symphony": "NOT",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "ntrn": {
        "base": "NTRN",
        "quote": "USDT",
        "ggshot": "NTRNUSDT",
        "ccxt": "NTRN/USDT",
        "hummingbot": "NTRN-USDT",
        "platform": "NTRN-USDT",
        "coingecko_id": "neutron-3",
        "symphony": "NTRN",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "ogn": {
        "base": "OGN",
        "quote": "USDT",
        "ggshot": "OGNUSDT",
        "ccxt": "OGN/USDT",
        "hummingbot": "OGN-USDT",
        "platform": "OGN-USDT",
        "coingecko_id": "origin-protocol",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "ondo": {
        "base": "ONDO",
        "quote": "USDT",
        "ggshot": "ONDOUSDT",
        "ccxt": "ONDO/USDT",
        "hummingbot": "ONDO-USDT",
        "platform": "ONDO-USDT",
        "coingecko_id": "ondo-finance",
        "symphony": "ONDO",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "one": {
        "base": "ONE",
        "quote": "USDT",
        "ggshot": "ONEUSDT", 
        "ccxt": "ONE/USDT",
        "hummingbot": "ONE-USDT",
        "platform": "ONE-USDT",
        "coingecko_id": "harmony",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "ont": {
        "base": "ONT",
        "quote": "USDT",
        "ggshot": "ONTUSDT",
        "ccxt": "ONT/USDT",
        "hummingbot": "ONT-USDT",
        "platform": "ONT-USDT",
        "coingecko_id": "ontology",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "op": {
        "base": "OP",
        "quote": "USDT",
        "ggshot": "OPUSDT",
        "ccxt": "OP/USDT",
        "hummingbot": "OP-USDT",
        "platform": "OP-USDT",
        "coingecko_id": "optimism",
        "symphony": "OP",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "ordi": {
        "base": "ORDI",
        "quote": "USDT",
        "ggshot": "ORDIUSDT",
        "ccxt": "ORDI/USDT",
        "hummingbot": "ORDI-USDT",
        "platform": "ORDI-USDT",
        "coingecko_id": "ordi",
        "symphony": "ORDI",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "pendle": {
        "base": "PENDLE",
        "quote": "USDT",
        "ggshot": "PENDLEUSDT",
        "ccxt": "PENDLE/USDT",
        "hummingbot": "PENDLE-USDT",
        "platform": "PENDLE-USDT",
        "coingecko_id": "pendle",
        "symphony": "PENDLE",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "people": {
        "base": "PEOPLE",
        "quote": "USDT",
        "ggshot": "PEOPLEUSDT",
        "ccxt": "PEOPLE/USDT",
        "hummingbot": "PEOPLE-USDT",
        "platform": "PEOPLE-USDT",
        "coingecko_id": "constitutiondao",
        "symphony": "PEOPLE",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "pyth": {
        "base": "PYTH",
        "quote": "USDT",
        "ggshot": "PYTHUSDT", 
        "ccxt": "PYTH/USDT",
        "hummingbot": "PYTH-USDT",
        "platform": "PYTH-USDT",
        "coingecko_id": "pyth-network",
        "symphony": "PYTH",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "qtum": {
        "base": "QTUM",
        "quote": "USDT",
        "ggshot": "QTUMUSDT",
        "ccxt": "QTUM/USDT",
        "hummingbot": "QTUM-USDT",
        "platform": "QTUM-USDT",
        "coingecko_id": "qtum",
        "symphony": "QTUM",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "rare": {
        "base": "RARE",
        "quote": "USDT",
        "ggshot": "RAREUSDT",
        "ccxt": "RARE/USDT",
        "hummingbot": "RARE-USDT",
        "platform": "RARE-USDT",
        "coingecko_id": "superrare",
        "symphony": "RARE",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "render": {
        "base": "RENDER",
        "quote": "USDT",
        "ggshot": "RENDERUSDT",
        "ccxt": "RENDER/USDT",
        "hummingbot": "RENDER-USDT",
        "platform": "RENDER-USDT",
        "coingecko_id": "render-token",
        "symphony": "RENDER",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "rlc": {
        "base": "RLC",
        "quote": "USDT",
        "ggshot": "RLCUSDT",
        "ccxt": "RLC/USDT",
        "hummingbot": "RLC-USDT",
        "platform": "RLC-USDT",
        "coingecko_id": "iexec-rlc",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "rose": {
        "base": "ROSE",
        "quote": "USDT",
        "ggshot": "ROSEUSDT",
        "ccxt": "ROSE/USDT",
        "hummingbot": "ROSE-USDT",
        "platform": "ROSE-USDT",
        "coingecko_id": "oasis-network",
        "symphony": "ROSE",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "rsr": {
        "base": "RSR",
        "quote": "USDT",
        "ggshot": "RSRUSDT",
        "ccxt": "RSR/USDT",
        "hummingbot": "RSR-USDT",
        "platform": "RSR-USDT",
        "coingecko_id": "reserve-rights-token",
        "symphony": "RSR",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "rune": {
        "base": "RUNE",
        "quote": "USDT",
        "ggshot": "RUNEUSDT",
        "ccxt": "RUNE/USDT",
        "hummingbot": "RUNE-USDT",
        "platform": "RUNE-USDT",
        "coingecko_id": "thorchain",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "rvn": {
        "base": "RVN",
        "quote": "USDT",
        "ggshot": "RVNUSDT",
        "ccxt": "RVN/USDT",
        "hummingbot": "RVN-USDT",
        "platform": "RVN-USDT",
        "coingecko_id": "ravencoin",
        "symphony": "RVN",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "sand": {
        "base": "SAND",
        "quote": "USDT",
        "ggshot": "SANDUSDT", 
        "ccxt": "SAND/USDT",
        "hummingbot": "SAND-USDT",
        "platform": "SAND-USDT",
        "coingecko_id": "the-sandbox",
        "symphony": "SAND",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "sei": {
        "base": "SEI",
        "quote": "USDT",
        "ggshot": "SEIUSDT",
        "ccxt": "SEI/USDT",
        "hummingbot": "SEI-USDT",
        "platform": "SEI-USDT",
        "coingecko_id": "sei-network",
        "symphony": "SEI",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "sfp": {
        "base": "SFP",
        "quote": "USDT",
        "ggshot": "SFPUSDT",
        "ccxt": "SFP/USDT",
        "hummingbot": "SFP-USDT",
        "platform": "SFP-USDT",
        "coingecko_id": "safemoon",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "sklus": {
        "base": "SKLUS",
        "quote": "USDT",
        "ggshot": "SKLUSUSDT",
        "ccxt": "SKLUS/USDT",
        "hummingbot": "SKLUS-USDT",
        "platform": "SKLUS-USDT",
        "coingecko_id": "skl",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "skl": {
        "base": "SKL",
        "quote": "USDT",
        "ggshot": "SKLUSDT",
        "ccxt": "SKL/USDT",
        "hummingbot": "SKL-USDT",
        "platform": "SKL-USDT",
        "coingecko_id": "skale",
        "symphony": "SKL",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "snx": {
        "base": "SNX",
        "quote": "USDT",
        "ggshot": "SNXUSDT",
        "ccxt": "SNX/USDT",
        "hummingbot": "SNX-USDT",
        "platform": "SNX-USDT",
        "coingecko_id": "havven",
        "symphony": "SNX",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "sol": {
        "base": "SOL",
        "quote": "USDT",
        "ggshot": "SOLUSDT",
        "ccxt": "SOL/USDT",
        "hummingbot": "SOL-USDT",
        "platform": "SOL-USDT",
        "coingecko_id": "solana",
        "symphony": "SOL",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "storj": {
        "base": "STORJ",
        "quote": "USDT",
        "ggshot": "STORJUSDT",
        "ccxt": "STORJ/USDT",
        "hummingbot": "STORJ-USDT",
        "platform": "STORJ-USDT",
        "coingecko_id": "storj",
        "symphony": "STORJ",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "strk": {
        "base": "STRK",
        "quote": "USDT",
        "ggshot": "STRKUSDT",
        "ccxt": "STRK/USDT",
        "hummingbot": "STRK-USDT",
        "platform": "STRK-USDT",
        "coingecko_id": "starknet",
        "symphony": "STRK",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "stx": {
        "base": "STX",
        "quote": "USDT",
        "ggshot": "STXUSDT",
        "ccxt": "STX/USDT",
        "hummingbot": "STX-USDT",
        "platform": "STX-USDT",
        "coingecko_id": "blockstack",
        "symphony": "STX",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "sui": {
        "base": "SUI",
        "quote": "USDT",
        "ggshot": "SUIUSDT",
        "ccxt": "SUI/USDT",
        "hummingbot": "SUI-USDT",
        "platform": "SUI-USDT",
        "coingecko_id": "sui",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": True,
        "websocket_cached": False
    },
    "s": {
        "base": "S",
        "quote": "USDT",
        "ggshot": "SUSDT",
        "ccxt": "S/USDT",
        "hummingbot": "S-USDT",
        "platform": "S-USDT",
        "coingecko_id": "s",
        "symphony": "S",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "sushi": {
        "base": "SUSHI",
        "quote": "USDT",
        "ggshot": "SUSHIUSDT",
        "ccxt": "SUSHI/USDT",
        "hummingbot": "SUSHI-USDT",
        "platform": "SUSHI-USDT",
        "coingecko_id": "sushi",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "sxp": {
        "base": "SXP",
        "quote": "USDT",
        "ggshot": "SXPUSDT",
        "ccxt": "SXP/USDT",
        "hummingbot": "SXP-USDT",
        "platform": "SXP-USDT",
        "coingecko_id": "swipe",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "tao": {
        "base": "TAO",
        "quote": "USDT",
        "ggshot": "TAOUSDT",
        "ccxt": "TAO/USDT",
        "hummingbot": "TAO-USDT",
        "platform": "TAO-USDT",
        "coingecko_id": "bittensor",
        "symphony": "TAO",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "theta": {
        "base": "THETA",
        "quote": "USDT",
        "ggshot": "THETAUSDT",
        "ccxt": "THETA/USDT",
        "hummingbot": "THETA-USDT",
        "platform": "THETA-USDT",
        "coingecko_id": "theta-token",
        "symphony": "THETA",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "tia": {
        "base": "TIA",
        "quote": "USDT",
        "ggshot": "TIAUSDT",
        "ccxt": "TIA/USDT",
        "hummingbot": "TIA-USDT",
        "platform": "TIA-USDT",
        "coingecko_id": "celestia",
        "symphony": "TIA",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "trb": {
        "base": "TRB",
        "quote": "USDT",
        "ggshot": "TRBUSDT",
        "ccxt": "TRB/USDT",
        "hummingbot": "TRB-USDT",
        "platform": "TRB-USDT",
        "coingecko_id": "tellor",
        "symphony": "TRB",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "trx": {
        "base": "TRX",
        "quote": "USDT",
        "ggshot": "TRXUSDT",
        "ccxt": "TRX/USDT",
        "hummingbot": "TRX-USDT",
        "platform": "TRX-USDT",
        "coingecko_id": "tron",
        "symphony": "TRX",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "turbo": {
        "base": "TURBO",
        "quote": "USDT",
        "ggshot": "TURBOUSDT",
        "ccxt": "TURBO/USDT",
        "hummingbot": "TURBO-USDT",
        "platform": "TURBO-USDT",
        "coingecko_id": "turbo",
        "symphony": "TURBO",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "twt": {
        "base": "TWT",
        "quote": "USDT",
        "ggshot": "TWTUSDT",
        "ccxt": "TWT/USDT",
        "hummingbot": "TWT-USDT",
        "platform": "TWT-USDT",
        "coingecko_id": "trust-wallet-token",
        "symphony": "TWT",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "vanry": {
        "base": "VANRY",
        "quote": "USDT",
        "ggshot": "VANRYUSDT",
        "ccxt": "VANRY/USDT",
        "hummingbot": "VANRY-USDT",
        "platform": "VANRY-USDT",
        "coingecko_id": "vanar-chain",
        "symphony": None,
        "symphony_compatible": False,
        "aster_compatible": False,
        "websocket_cached": False
    },
    "vet": {
        "base": "VET",
        "quote": "USDT",
        "ggshot": "VETUSDT",
        "ccxt": "VET/USDT",
        "hummingbot": "VET-USDT",
        "platform": "VET-USDT",
        "coingecko_id": "vechain",
        "symphony": "VET",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "wif": {
        "base": "WIF",
        "quote": "USDT",
        "ggshot": "WIFUSDT",
        "ccxt": "WIF/USDT",
        "hummingbot": "WIF-USDT",
        "platform": "WIF-USDT",
        "coingecko_id": "dogwifcoin",
        "symphony": "WIF",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "wld": {
        "base": "WLD",
        "quote": "USDT",
        "ggshot": "WLDUSDT",
        "ccxt": "WLD/USDT",
        "hummingbot": "WLD-USDT",
        "platform": "WLD-USDT",
        "coingecko_id": "worldcoin-wld",
        "symphony": "WLD",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "woo": {
        "base": "WOO",
        "quote": "USDT",
        "ggshot": "WOOUSDT",
        "ccxt": "WOO/USDT",
        "hummingbot": "WOO-USDT",
        "platform": "WOO-USDT",
        "coingecko_id": "woo-network",
        "symphony": "WOO",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "w": {
        "base": "W",
        "quote": "USDT",
        "ggshot": "WUSDT",
        "ccxt": "W/USDT",
        "hummingbot": "W-USDT",
        "platform": "W-USDT",
        "coingecko_id": "wormhole",
        "symphony": "W",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "xrp": {
        "base": "XRP",
        "quote": "USDT",
        "ggshot": "XRPUSDT",
        "ccxt": "XRP/USDT",
        "hummingbot": "XRP-USDT",
        "platform": "XRP-USDT",
        "coingecko_id": "ripple",
        "symphony": "XRP",
        "symphony_compatible": True,
        "aster_compatible": True,
        "websocket_cached": True
    },
    "yfi": {
        "base": "YFI",
        "quote": "USDT",
        "ggshot": "YFIUSDT",
        "ccxt": "YFI/USDT",
        "hummingbot": "YFI-USDT",
        "platform": "YFI-USDT",
        "coingecko_id": "yearn-finance",
        "symphony": "YFI",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "zil": {
        "base": "ZIL",
        "quote": "USDT",
        "ggshot": "ZILUSDT",
        "ccxt": "ZIL/USDT",
        "hummingbot": "ZIL-USDT",
        "platform": "ZIL-USDT",
        "coingecko_id": "zilliqa",
        "symphony": "ZIL",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "zro": {
        "base": "ZRO",
        "quote": "USDT",
        "ggshot": "ZROUSDT",
        "ccxt": "ZRO/USDT",
        "hummingbot": "ZRO-USDT",
        "platform": "ZRO-USDT",
        "coingecko_id": "layerzero",
        "symphony": "ZRO",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    },
    "zrx": {
        "base": "ZRX",
        "quote": "USDT",
        "ggshot": "ZRXUSDT",
        "ccxt": "ZRX/USDT",
        "hummingbot": "ZRX-USDT",
        "platform": "ZRX-USDT",
        "coingecko_id": "0x",
        "symphony": "ZRX",
        "symphony_compatible": True,
        "aster_compatible": False,
        "websocket_cached": True
    }
}

def get_all_symbols() -> List[str]:
    """Get all supported symbol keys"""
    return list(SYMBOL_REGISTRY.keys())

def get_symbol_data(symbol_key: str) -> Optional[Dict[str, str]]:
    """Get all format data for a symbol key"""
    return SYMBOL_REGISTRY.get(symbol_key)

def find_symbol_by_format(symbol: str, format_type: str) -> Optional[str]:
    """Find symbol key by any format (ggshot, ccxt, hummingbot, etc.)"""
    for key, data in SYMBOL_REGISTRY.items():
        if data.get(format_type) == symbol:
            return key
    return None

def is_websocket_cached(symbol: str, format_type: str = "ccxt") -> bool:
    """
    Check if a symbol is WebSocket-cached (real-time price data available).

    Args:
        symbol: Symbol in specified format (e.g., 'BTC/USDT' for ccxt)
        format_type: Format type (default: 'ccxt')

    Returns:
        True if symbol is WebSocket-cached, False otherwise
    """
    symbol_key = find_symbol_by_format(symbol, format_type)
    if not symbol_key:
        return False

    symbol_data = get_symbol_data(symbol_key)
    return symbol_data.get("websocket_cached", False) if symbol_data else False

def get_websocket_cached_count() -> int:
    """Get count of WebSocket-cached symbols."""
    return sum(1 for data in SYMBOL_REGISTRY.values() if data.get("websocket_cached", False))