#!/usr/bin/env python
"""
Generate a list of BitMEX symbols using direct CCXT library access.
This script outputs a Python file with BitMEX symbol mappings that can be 
imported and used to update the EXCHANGE_SYMBOL_MAP in CCXTMCPAdapter.
"""

import os
import sys
import json
import ccxt
from pathlib import Path
from typing import Dict, List

def get_bitmex_symbols(testnet: bool = True) -> Dict[str, str]:
    """
    Fetch BitMEX symbols using CCXT and create a mapping from standard to BitMEX format.
    
    Args:
        testnet: Whether to use BitMEX testnet
        
    Returns:
        Dictionary with mappings from standard to BitMEX symbols
    """
    # Create BitMEX client with testnet setting if needed
    bitmex_config = {
        'enableRateLimit': True
    }
    
    if testnet:
        bitmex_config['test'] = True  # Enable testnet
    
    bitmex = ccxt.bitmex(bitmex_config)
    
    # Load all market definitions from BitMEX
    print(f"Loading {'testnet' if testnet else 'mainnet'} BitMEX markets...")
    markets = bitmex.load_markets()
    
    print(f"Loaded {len(bitmex.symbols)} symbols from BitMEX")
    
    # Create mappings from standard to BitMEX symbols
    mappings = {}
    
    # Process each market
    for symbol in bitmex.symbols:
        market = markets[symbol]
        
        # Extract base and quote currencies
        base = market['base']
        quote = market['quote']
        
        # For perpetual contracts, create standard symbol format (BASE/QUOTE)
        if 'swap' in market['info']['typ'].lower() or market['swap']:
            standard_symbol = f"{base}/{quote}"
            mappings[standard_symbol] = symbol
            
            # Print details about this mapping
            print(f"Mapped {standard_symbol} ↔ {symbol}")
            print(f"  Type: {market['type']}")
            print(f"  Base/Quote: {base}/{quote}")
            if 'settle' in market and market['settle']:
                print(f"  Settlement: {market['settle']}")
            print(f"  Contract Size: {market.get('contractSize', 1)}")
            print(f"  Inverse: {market.get('inverse', False)}")
            print()
    
    return mappings

def save_mappings(mappings: Dict[str, str], output_path: str = None) -> None:
    """
    Save the symbol mappings to a Python file.
    
    Args:
        mappings: Dictionary of symbol mappings
        output_path: Path to save the output file
    """
    if output_path is None:
        output_path = Path(__file__).parent / "bitmex_symbol_mappings.py"
    
    code = f"""#!/usr/bin/env python
\"\"\"
BitMEX symbol mappings generated by {Path(__file__).name}.
This file contains mappings from standard symbols (like 'BTC/USD') to 
BitMEX-specific symbols.
\"\"\"

from typing import Dict

# Mapping from standard symbols to BitMEX-specific symbols
BITMEX_SYMBOL_MAPPINGS: Dict[str, str] = {json.dumps(mappings, indent=4)}

# Reverse mapping from BitMEX to standard symbols
# This is useful for converting exchange responses back to standard format
BITMEX_REVERSE_MAPPINGS: Dict[str, str] = {{
    bitmex_symbol: standard_symbol
    for standard_symbol, bitmex_symbol in BITMEX_SYMBOL_MAPPINGS.items()
}}
"""
    
    with open(output_path, 'w') as f:
        f.write(code)
    
    print(f"Saved BitMEX symbol mappings to {output_path}")

if __name__ == "__main__":
    # Parse command line arguments
    import argparse
    parser = argparse.ArgumentParser(description='Generate BitMEX symbol mappings')
    parser.add_argument('--mainnet', action='store_true', help='Use BitMEX mainnet instead of testnet')
    parser.add_argument('--output', type=str, help='Output file path', default=None)
    args = parser.parse_args()
    
    # Get the mappings
    mappings = get_bitmex_symbols(testnet=not args.mainnet)
    
    # Save the mappings
    save_mappings(mappings, args.output)